/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 85142d631feb0dc44632b6ddd906dd97 */

/* creation time: Tue Feb 10 17:59:35 2015 */
/* tdr version: 2.4.21914, build at 20110728 */

#ifndef _GameConfig_metalib_h_
#define _GameConfig_metalib_h_

namespace GameConfig
{


class MetaLib
{
    public:
        static int getVersion()
        {
            return 1;
        }

        static const char* getName()
        {
            return "GameConfig";
        }

        static const char* getMd5Sum()
        {
            return "85142d631feb0dc44632b6ddd906dd97";
        }

        static const char* getTdrVersion()
        {
            return "2.4.21914, build at 20110728";
        }
};


}
#endif
