/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 85142d631feb0dc44632b6ddd906dd97 */

/* creation time: Tue Feb 10 17:59:35 2015 */
/* tdr version: 2.4.21914, build at 20110728 */

#ifndef _TdrKeywords_h_
#define _TdrKeywords_h_

#include "TdrBuf.h"
#include "TdrError.h"
#include "TdrBufUtil.h"
#include "TdrTypeUtil.h"


using tsf4g_tdr::TdrError;
using tsf4g_tdr::TdrReadBuf;
using tsf4g_tdr::TdrWriteBuf;

namespace GameConfig
{


enum
{
    MAX_WORLD_PER_CLUSTER = 40, // 一个集群中拥有的世界服务器的数量
    MAX_SERVER_BUS_ADDR_LEN = 64, // 服务器的ZMQ BUS的地址的最大长度，格式为 ip:port
    MAX_SERVER_BUS_NUMBER = 100, // 服务器最大支持的ZMQ通信通道的数量
    MAX_HANDLER_NUMBER = 16384, // 服务器支持的最大的消息处理Handler的数量
    MAX_ZONE_PER_WORLD = 8, // 当前单个世界能支持的最大分区
    MAX_SESSIONKEY_LENGTH = 64, // 玩家session key的最大长度
    ROLE_TABLE_SPLIT_FACTOR = 8, // ROLEDB数据库访问的分表因子
    ACCOUNT_TABLE_SPLIT_FACTOR = 8, // AccountDB数据库访问的分表因子
    NAME_TABLE_SPLIT_FACTOR = 8, // NameDB数据库访问的分表因子
    MAX_NICK_NAME_LENGTH = 64, // 玩家名字的最大长度
    GAME_START_YEAR = 2014, // 游戏正式开始运营的年份
    UNACTIVE_ROLE_TIMEOUT = 7200, // 判断玩家不活跃的超时时间,120*60s
    TICK_TIMEVAL_UPDATEDB = 300, // 更新玩家数据库的时间间隔，5*60s
    ONE_MIN_TIMEOUT = 60, // 一分钟定时
    TEN_SECOND_TIMER = 10, // 10秒钟定时
    GAME_ROLEUNIT_CONFIG_ID = 1, // 游戏主角的ID
    MAX_REP_BLOCK_NUM = 280, // 玩家最大背包格子数
    MAX_UNIT_ITEM_SLOT = 5, // 战斗单位身上物品槽最大数目
    MAX_FIGHT_CD_NUM = 6, // 战斗时最多支持的计算CD的数目
    MAX_ROLE_BIRTH_NUM = 2, // 游戏支持的最大出生表的行数
    MAX_GAME_ITEM_CONFIG_NUM = 1000, // 游戏支持的物品配置最大数目
    MAX_FIGHT_UNIT_NUM = 500, // 游戏支持的战斗单位的最大数目
    MAX_FIGHTUNIT_ON_FORM = 5, // 玩家阵型上阵单位的数量上限
    MAX_FIGHT_AI_POS_NUM = 150, // 战斗单位AI中最多支持的行动点查找数目
    MAX_ROLE_FIGHTUNIT_NUM = 30, // 玩家能拥有的战斗单位的数量上限
    MAX_CAMP_FIGHT_UNIT_NUM = 10, // 游戏战斗单个阵营允许上阵的最大战斗单位数
    MAX_COMBAT_TRAP_NUM = 99, // 游戏战斗战场上最大放置的机关数目
    MAX_BATTLE_CROSS_NUM = 500, // 游戏支持的最大战斗关卡配置数目
    MAX_CROSS_MONSTER_CONFIG_NUM = 500, // 游戏支持的最大关卡怪物组配置数目
    MAX_FIGHT_JUDGE_CONFIG_NUM = 50, // 游戏支持的最大战斗胜负条件数目
    MAX_FIGHTUNIT_AI_CONFIG_NUM = 50, // 游戏支持的最大战斗单位AI数目
    MAX_MONSTER_CONFIG_NUM = 1000, // 游戏支持的最大战斗怪物数目
    MAX_FIGHT_SKILL_CONFIG_NUM = 1000, // 战斗技能的最大数目
    MAX_SKILL_RANGE_CONFIG_NUM = 100, // 游戏支持的最大技能释放距离配置数目
    MAX_SKILL_AREA_CONFIG_NUM = 500, // 游戏支持的最大技能释放范围配置数目
    MAX_SKILL_SCORE_CONFIG_NUM = 500, // 游戏支持的最大技能修正配置数目
    MAX_SKILL_DAMAGE_CONFIG_NUM = 500, // 游戏支持的最大技能伤害配置数目
    MAX_FIGHT_BUFF_CONFIG_NUM = 3000, // 游戏支持的最大BUFF配置数目
    MAX_DROP_REWARD_CONFIG_NUM = 1000, // 游戏支持的最大战斗奖励配置数目
    MAX_FIGHT_UNIT_BUFF_NUM = 32, // 单个战斗单位能附加的Buff数量上限
    MAX_JOINT_ATTACK_CONFIG_NUM = 1000, // 支持的技能伙伴合击配置的上限
    MAX_COMBAT_TRAP_CONFIG_NUM = 1000, // 支持的战场机关配置的上限
};


enum ServerState
{
    SERVER_STATE_IDLE = 1,
    SERVER_STATE_BUSY = 2,
    SERVER_STATE_FULL = 3,
};
enum GameUnitType
{
    EUT_ROLE = 1, // 角色
};
enum EUnitStatus
{
    EGUS_ONLINE = 1,
    EGUS_LOGOUT = 2,
    EGUS_ISGM = 4,
    EGUS_DELETE = 8,
};
enum LogoutReasonType
{
    LOGOUT_REASON_REQUEST = 140,
    LOGOUT_REASON_KICKOFF = 141,
};
enum ResourceType
{
    RESOURCE_TYPE_INVALID = 0, // 非法的资源类型
    RESOURCE_TYPE_COIN = 1, // 游戏金币
    RESOURCE_TYPE_CASH = 2, // 游戏充值货币
    RESOURCE_TYPE_ENERGY = 3, // 玩家体力值
    RESOURCE_TYPE_MAX = 4, // 游戏资源最大
};
enum FightProfType
{
    FIGHT_PROF_MYRMIDON = 101, // 剑士，近战刺客
    FIGHT_PROF_FIGHTER = 102, // 战士，近战肉
    FIGHT_PROF_MERCENARY = 103, // 佣兵
    FIGHT_PROF_ARMOR = 104, // 重骑士
    FIGHT_PROF_ARCHE = 105, // 弓箭手
    FIGHT_PROF_THIEF = 106, // 盗贼
    FIGHT_PROF_PRIESTS = 107, // 牧师
    FIGHT_PROF_MAGES = 108, // 魔道士
    FIGHT_PROF_DARKMAGE = 109, // 暗法师
};
enum FightAttributeType
{
    FIGHT_ATTR_HP = 0, // 生命值属性
    FIGHT_ATTR_SPEED = 1, // 速度值属性,决定行动步长
    FIGHT_ATTR_ATK = 2, // 攻击值属性
    FIGHT_ATTR_AP = 3, // 法强值属性
    FIGHT_ATTR_DEF = 4, // 防御值属性
    FIGHT_ATTR_SR = 5, // 魔抗值属性
    FIGHT_ATTR_HIT = 6, // 命中值属性
    FIGHT_ATTR_AVO = 7, // 闪避值属性
    FIGHT_ATTR_CRI = 8, // 暴击值属性
    FIGHT_ATTR_TOU = 9, // 韧性值属性
    FIGHT_ATTR_ACC = 10, // 精准值属性
    FIGHT_ATTR_PAR = 11, // 招架值属性
    FIGHT_ATTR_HUDUN = 12, // 护盾属性
    FIGHT_ATTR_FANJI = 13, // 反击属性
    FIGHT_ATTR_LIANJI = 14, // 连击属性
    FIGHT_ATTR_HPMAX = 15, // 最大生命属性
    FIGHT_ATTR_XIANGONG = 16, // 先攻值属性,决定出手顺序
    FIGHT_ATTR_MAX = 17, // 属性最大的，程序使用
};
enum UnitDirectionType
{
    DIRECTION_SOUTH_EAST = 1, // 右下
    DIRECTION_EAST = 2, // 右
    DIRECTION_NORTH_EAST = 3, // 右上
    DIRECTION_NORTH = 4, // 上
    DIRECTION_NORTH_WEST = 5, // 左上
    DIRECTION_WEST = 6, // 左
    DIRECTION_SOUTH_WEST = 7, // 左下
    DIRECTION_SOUTH = 8, // 下
};
enum GameItemType
{
    REP_ITEM_TYPE_INVALID = 100, // 非法的物品类型
    REP_ITEM_TYPE_PROP = 101, // 道具类型
    REP_ITEM_TYPE_EQUIP = 102, // 装备类型
};
enum SuperPositionType
{
    ITEM_SUPERPOSITION_TYPE_INVALID = 100, // 非法的物品叠加类型
    ITEM_SUPERPOSITION_TYPE_YES = 101, // 可叠加的物品类型
    ITEM_SUPERPOSITION_TYPE_NO = 102, // 不可叠加的物品类型
};
enum EquipSlotType
{
    EQUIP_SLOT_TYPE_INVALID = 0, // 非法的装备槽类型
    EQUIP_SLOT_TYPE_WUQI = 1, // 武器
    EQUIP_SLOT_TYPE_SHANGZHUANG = 2, // 上装
    EQUIP_SLOT_TYPE_XIAZHUANG = 3, // 下装
    EQUIP_SLOT_TYPE_SHIZHUANG = 4, // 时装
    EQUIP_SLOT_TYPE_JIEZHI = 5, // 戒指
    EQUIP_SLOT_TYPE_XIANGLIAN = 6, // 项链
    EQUIP_SLOT_TYPE_YAODAI = 7, // 腰带
    EQUIP_SLOT_TYPE_MAX = 8, // 最大类型，方便程序使用
};
enum UnitAIType
{
    UNIT_AI_TYPE_GONGJI = 0, // 攻击
    UNIT_AI_TYPE_ZHUIJI = 1, // 追击
    UNIT_AI_TYPE_POJIN = 2, // 迫近
    UNIT_AI_TYPE_JIAOSHOU = 3, // 交手
    UNIT_AI_TYPE_HEJI = 4, // 合击
    UNIT_AI_TYPE_BEIJI = 5, // 被击
    UNIT_AI_TYPE_BEIZU = 6, // 被阻
    UNIT_AI_TYPE_BEIAI = 7, // 被碍
    UNIT_AI_TYPE_ZHILIAO = 8, // 治疗
    UNIT_AI_TYPE_ZUDANG = 9, // 阻挡
    UNIT_AI_TYPE_FANGAI = 10, // 妨碍
    UNIT_AI_TYPE_MUBIAO = 11, // 目标
    UNIT_AI_TYPE_JISHA = 12, // 击杀
    UNIT_AI_TYPE_ZHENJIU = 13, // 拯救
    UNIT_AI_TYPE_MAX = 14, // 策略最大
};
enum SkillUseType
{
    SKILL_USE_ACTIVE = 1, // 主动使用的技能类型
    SKILL_USE_ON_STAGE = 2, // 登场使用的技能类型
    SKILL_USE_ROUNDACTION = 3, // 单位回合前使用的技能类型
    SKILL_USE_JIAJI = 4, // 夹击的技能使用类型
    SKILL_USE_LIANJI = 5, // 连击的技能使用类型
    SKILL_USE_HEJI = 6, // 合击的技能使用类型
    SKILL_USE_FANJI = 7, // 反击的技能使用类型
    SKILL_USE_AI = 8, // AI使用的技能类型
};
enum SkillTargetType
{
    SKILL_TARGET_INVALID = 0, // 无
    SKILL_TARGET_SELF = 1, // 自身
    SKILL_TARGET_CAMP = 2, // 友方
    SKILL_TARGET_NOT_ENEMY = 3, // 非敌
    SKILL_TARGET_ENEMY = 4, // 敌人
    SKILL_TARGET_ALL = 7, // 所有人
    SKILL_TARGET_GROUND = 8, // 对地的技能
};
enum FightCampType
{
    FIGHT_CAMP_INVALID = 0, // 非法的战斗阵营
    FIGHT_CAMP_ACTIVE = 1, // 主动发起战斗方
    FIGHT_CAMP_PASSIVE = 2, // 被动接受战斗方
    FIGHT_CAMP_NEUTRAL = 3, // 中立战斗阵营
};
enum CombatDirectionType
{
    COMBAT_DIRECTION_INVALID = 0, // 非法的方向信息
    COMBAT_DIRECTION_EAST = 1, // 方向向右
    COMBAT_DIRECTION_NORTH = 2, // 方向向上
    COMBAT_DIRECTION_WEST = 3, // 方向向左
    COMBAT_DIRECTION_SOUTH = 4, // 方向向下
};
enum CombatUnitAIType
{
    COMBAT_UNIT_AI_JIAOSHOU = 0, // 交手
    COMBAT_UNIT_AI_HEJI = 1, // 合击
    COMBAT_UNIT_AI_JISHA = 2, // 击杀
    COMBAT_UNIT_AI_BEIJI = 3, // 被击
    COMBAT_UNIT_AI_ZHUIJI = 4, // 追击
    COMBAT_UNIT_AI_RESERVE2 = 5, // 保留2
    COMBAT_UNIT_AI_RESERVE3 = 6, // 保留3
    COMBAT_UNIT_AI_RESERVE4 = 7, // 保留4
    COMBAT_UNIT_AI_RESERVE5 = 8, // 保留5
    COMBAT_UNIT_AI_RESERVE6 = 9, // 保留6
    COMBAT_UNIT_AI_RESERVE7 = 10, // 保留7
    COMBAT_UNIT_AI_RESERVE8 = 11, // 保留8
    COMBAT_UNIT_AI_RESERVE9 = 12, // 保留9
    COMBAT_UNIT_AI_RESERVE10 = 13, // 保留10
    COMBAT_UNIT_AI_SKILL1 = 14, // 技能1
    COMBAT_UNIT_AI_SKILL2 = 15, // 技能2
    COMBAT_UNIT_AI_SKILL3 = 16, // 技能3
    COMBAT_UNIT_AI_SKILL4 = 17, // 技能4
    COMBAT_UNIT_AI_SKILL5 = 18, // 技能5
    COMBAT_UNIT_AI_SKILL6 = 19, // 技能6
};
enum BuffTriggerType
{
    BUFF_TRIGGER_IMMEDIATELY = 0, // 即时生效
    BUFF_TRIGGER_ROUNDBEGIN = 1, // 回合开始
    BUFF_TRIGGER_ROUNDEND = 2, // 回合结束
    BUFF_TRIGGER_ACTIONROUNDBEGIN = 3, // 行动回合开始
    BUFF_TRIGGER_ACTIONROUNDEND = 4, // 行动回合结束
    BUFF_TRIGGER_MOVE = 5, // 移动触发BUFF
    BUFF_TRIGGER_UNDERATTACK = 10, // 被攻击
    BUFF_TRIGGER_PROCESSDAMAGE = 15, // 伤害处理触发
    BUFF_TRIGGER_UNDERDAMAGE = 20, // 被伤害
    BUFF_TRIGGER_DODGE = 30, // 闪避成功
};
enum BuffOverlyingType
{
    BUFF_OVERLYING_ALL = 0, // 无叠加限制
    BUFF_OVERLYING_ZHONGDU = 1, // 中毒类型
    BUFF_OVERLYING_KANGDU = 2, // 抗毒类型
    BUFF_OVERLYING_GONGJI = 10, // 攻击属性
    BUFF_OVERLYING_BEIKE = 20, // 被击被克
    BUFF_OVERLYING_FANZHI = 30, // 被击反制
    BUFF_OVERLYING_JINGZHIACTION = 100, // 禁止行动
    BUFF_OVERLYING_JINgZHIMOVE = 101, // 禁止移动
    BUFF_OERLYING_JINGZHINORMALATK = 102, // 禁止普攻
    BUFF_OVERLYING_JINGZHISKILLATK = 103, // 禁止发招
    BUFF_OVERLYING_JINGZHIITEM = 104, // 禁止道具
    BUFF_OVERLYING_YINGGONG = 1001, // 硬功修正
    BUFF_OVERLYING_RUANGONG = 1002, // 软功修正
    BUFF_OVERLYING_NEIGONG = 1003, // 内功修正
    BUFF_OVERLYING_QINGGONG = 1004, // 轻功修正
    BUFF_OVERLYING_YANGONG = 1005, // 眼功修正
    BUFF_OVERLYING_ERGONG = 1006, // 耳功修正
    BUFF_OVERLYING_MINGZHONG = 1007, // 命中修正
    BUFF_OVERLYING_SHANBI = 1008, // 闪避修正
    BUFF_OVERLYING_JINGZHUN = 1009, // 精准修正
    BUFF_OVERLYING_ZHAOJIA = 1010, // 招架修正
    BUFF_OVERLYING_BAOJI = 1011, // 暴击修正
    BUFF_OVERLYING_JIANREN = 1012, // 坚韧修正
};
enum BuffOperaType
{
    BUFF_OPERA_INVALID = 0, // 没有操作类型
    BUFF_OPERA_ADDATTR = 1, // 属性加
    BUFF_OPERA_ADDRATEATTR = 2, // 属性百分比
    BUFF_OPERA_REPLACEATTR = 3, // 属性替换
    BUFF_OPERA_LOCKATTR = 4, // 属性锁定
    BUFF_OPERA_ADDBUFF = 10, // 附加新BUFF
    BUFF_OPERA_UNARM = 11, // 缴械，目标武器失效
    BUFF_OPERA_IGNOREJOINTATK = 12, // 无视围攻，该BUFF使围攻无效
    BUFF_OPERA_UNBENDING = 13, // 不屈
    BUFF_OPERA_GUARD = 14, // 守护
    BUFF_OPERA_FORBIDROUND = 100, // 禁止开始战斗回合
    BUFF_OPERA_FORBIDMOVE = 101, // 禁止回合移动
    BUFF_OPERA_FORBIDACTION = 103, // 禁止回合行动
};
enum BuffTargetType
{
    BUFF_TARGET_INVALID = 0, // 没有目标
    BUFF_TARGET_SELF = 1, // 携带者
    BUFF_TARGET_CAST = 2, // 发动者
    BUFF_TARGET_TRIGGER = 3, // 触发者
};
enum BuffParamType
{
    BUFF_PARAM_TARGET = 0, // 目标参数
    BUFF_PARAM_ATTRBUFF = 1, // 属性类型或状态ID
    BUFF_PARAM_VALUE = 2, // 效果值参数
};
enum BuffEffectType
{
    BUFF_EFFECT_INVALID = 0, // 非法的持久类型
    BUFF_EFFECT_FOREVER = 1, // 永久生效
    BUFF_EFFECT_ROUNDS = 2, // Buff消失时清除
};
enum RewardType
{
    REWARD_TYPE_INVALID = 0, // 非法的战斗奖励类型
    REWARD_TYPE_ITEM = 2, // 奖励物品类型
    REWARD_TYPE_FORMEXP = 5, // 增加阵型中单位经验
};
enum CombatResultType
{
    COMBAT_RESULT_INVALID = 0, // 非法的战斗结果类型
    COMBAT_RESULT_ACTIVE_WIN = 1, // 主动战斗方获胜
    COMBAT_RESULT_PASSIVE_WIN = 2, // 被动战斗方获胜
};
enum FaceModifierType
{
    FACE_MODIFIER_DODGE = 0, // 闪避的修正
    FACE_MODIFIER_BLOCK = 1, // 格挡的修正
    FACE_MODIFIER_JIANREN = 2, // 坚韧的修正
    FACE_MODIFIER_DEFENCE = 3, // 防御强度的修正
    FACE_MODIFIER_DAMAGE = 4, // 伤害的修正
};
enum CombatTrapType
{
    COMBAT_TRAP_INVALID = 0, // 非法的机关类型
    COMBAT_TRAP_TRAP = 1, // 陷阱类型
    COMBAT_TRAP_ORGAN = 2, // 机关类型
};
enum TrapTriggerType
{
    TRAP_TRIGGER_INVALID = 0, // 非法的触发类型
    TRAP_TRIGGER_MOVEON = 1, // 停止触发
    TRAP_TRIGGER_LEAVE = 2, // 离开触发
    TRAP_TRIGGER_SKILL = 3, // 技能触发
    TRAP_TRIGGER_PASSIVE = 4, // 被动触发
    TRAP_TRIGGER_DESTROY = 5, // 破坏触发
};
enum TrapInterruptType
{
    TRAP_INTERRUPT_INVALID = 0, // 非法的目标打断类型
    TRAP_INTERRUPT_NONE = 1, // 不打断目标的行动
    TRAP_INTERRUPT_MOVE = 2, // 打断目标的移动
    TRAP_INTERRUPT_ACTION = 3, // 打断目标的行动
    TRAP_INTERRUPT_ALL = 4, // 全部打断，包括目标的行动和移动
};
enum TrapVisiableType
{
    TRAP_VISIBALE_INVALID = 0, // 非法的可见类型
    TRAP_VISIBALE_NONE = 1, // 全部不可见
    TRAP_VISIBALE_SELF = 2, // 己方可见
    TRAP_VISIBALE_ALL = 3, // 全部都可见，己方和地方
};
enum SkillScriptCallType
{
    SKILL_SCRIPT_CALL_INVALID = 0, // 非法的调用类型
    SKILL_SCRIPT_CALL_DAMAGE = 1, // 伤害计算时的调用类型
    SKILL_SCRIPT_CALL_SKILLDONE = 2, // 技能结束后的调用类型
    SKILL_SCRIPT_CALL_CHIEFDODGE = 3, // 主要目标闪避后的调用类型
};
enum SkillSpecialFuncType
{
    SKILL_SPECIAL_FUNC_INVALID = 0, // 非法的特殊功能类型
    SKILL_SPECIAL_FUNC_EXCHANGEPOS = 1, // 移形换位，和对方交换位置
};
enum SSkillHitType
{
    SKILL_HIT_INVALID = 0, // 非法的技能命中类型
    SKILL_HIT_NOHIT = 1, // 不检查命中
    SKILL_HIT_CHIEFDODGE = 2, // 命中主要目标
    SKILL_HIT_CHIEFNODODGE = 3, // 没有命中主要目标
};


#pragma pack(1)


#pragma pack()

}
#endif
