/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* creation time: Tue Feb 10 17:59:35 2015 */
/* tdr version: 2.4.21914, build at 20110728 */

#ifndef _TDR_THIRD_PARTY_H_
#define _TDR_THIRD_PARTY_H_

namespace tsf4g_tdr_third_party
{


char* strptime(const char* buf, const char* format, struct tm* timeptr);

}
#endif
