/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* creation time: Tue Feb 10 17:59:35 2015 */
/* tdr version: 2.4.21914, build at 20110728 */

#ifndef _TDR_TYPE_H_
#define _TDR_TYPE_H_

#include "TdrPal.h"
#include "TdrBuf.h"
#include "TdrError.h"
#include "TdrTime.h"

namespace tsf4g_tdr
{


class TdrTypeUtil
{
    public:
        static TdrError::ErrorType str2TdrIP(tdr_ip_t& dest, const char *pszIP);
        static TdrError::ErrorType str2TdrTime(tdr_time_t& dest, const char *pszTime);
        static TdrError::ErrorType str2TdrDate(tdr_date_t& dest, const char *pszDate);
        static TdrError::ErrorType str2TdrDateTime(tdr_datetime_t& dest, const char *pszDateTime);
        static TdrError::ErrorType UTC2TdrDateTime(tdr_datetime_t& dest, time_t utcTime);


        static TdrError::ErrorType tdrIp2Str(TdrWriteBuf& dest, tdr_ip_t src);

        static TdrError::ErrorType tdrTime2Str(TdrWriteBuf& dest, tdr_time_t src)
        {
            return TdrTime(src).print2Buf(dest);
        }

        static TdrError::ErrorType tdrDate2Str(TdrWriteBuf& dest, tdr_date_t src)
        {
            return TdrDate(src).print2Buf(dest);
        }

        static TdrError::ErrorType tdrDateTime2Str(TdrWriteBuf& dest, tdr_datetime_t src)
        {
            return TdrDateTime(src).print2Buf(dest);
        }

        static TdrError::ErrorType tdrDateTime2UTC(time_t& dest, tdr_datetime_t src);

    public:
        static int compareTdrTime(tdr_time_t left, tdr_time_t right);
        static int compareTdrDate(tdr_date_t left, tdr_date_t right);
        static int compareTdrDateTime(tdr_datetime_t left, tdr_datetime_t right);

    public:
        static size_t wstrlen(const tdr_wchar_t* wstr);
};

}
#endif
