// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameProtocol.MsgID.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GameProtocol.MsgID.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* ProtocolMsgID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_GameProtocol_2eMsgID_2eproto() {
  protobuf_AddDesc_GameProtocol_2eMsgID_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GameProtocol.MsgID.proto");
  GOOGLE_CHECK(file != NULL);
  ProtocolMsgID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GameProtocol_2eMsgID_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_GameProtocol_2eMsgID_2eproto() {
}

void protobuf_AddDesc_GameProtocol_2eMsgID_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\030GameProtocol.MsgID.proto*\222\034\n\rProtocolM"
    "sgID\022\036\n\032MSGID_PROTOCOL_INVALID_MSG\020\000\022%\n "
    "MSGID_ACCOUNT_CREATEROLE_REQUEST\020\350\007\022&\n!M"
    "SGID_ACCOUNT_CREATEROLE_RESPONSE\020\351\007\022#\n\036M"
    "SGID_ACCOUNT_LISTZONE_REQUEST\020\352\007\022$\n\037MSGI"
    "D_ACCOUNT_LISTZONE_RESPONSE\020\353\007\022%\n MSGID_"
    "ACCOUNT_DELETEROLE_REQUEST\020\354\007\022&\n!MSGID_A"
    "CCOUNT_DELETEROLE_RESPONSE\020\355\007\022#\n\036MSGID_A"
    "CCOUNT_LISTROLE_REQUEST\020\356\007\022$\n\037MSGID_ACCO"
    "UNT_LISTROLE_RESPONSE\020\357\007\022\037\n\032MSGID_LOGOUT"
    "SERVER_REQUEST\020\360\007\022 \n\033MSGID_LOGOUTSERVER_"
    "RESPONSE\020\361\007\022\035\n\030MSGID_ADDNEWNAME_REQUEST\020"
    "\362\007\022\036\n\031MSGID_ADDNEWNAME_RESPONSE\020\363\007\022\035\n\030MS"
    "GID_DELETENAME_REQUEST\020\364\007\022\036\n\031MSGID_DELET"
    "ENAME_RESPONSE\020\365\007\022\'\n\"MSGID_ACCOUNTDB_ADD"
    "ACCOUNT_REQUEST\020\270\010\022(\n#MSGID_ACCOUNTDB_AD"
    "DACCOUNT_RESPONSE\020\271\010\022#\n\036MSGID_ACCOUNTDB_"
    "DELETE_REQUEST\020\272\010\022$\n\037MSGID_ACCOUNTDB_DEL"
    "ETE_RESPONSE\020\273\010\022\"\n\035MSGID_ACCOUNTDB_FETCH"
    "_REQUEST\020\274\010\022#\n\036MSGID_ACCOUNTDB_FETCH_RES"
    "PONSE\020\275\010\022#\n\036MSGID_ACCOUNTDB_UPDATE_REQUE"
    "ST\020\276\010\022$\n\037MSGID_ACCOUNTDB_UPDATE_RESPONSE"
    "\020\277\010\022%\n MSGID_REGAUTH_REGACCOUNT_REQUEST\020"
    "\303\010\022&\n!MSGID_REGAUTH_REGACCOUNT_RESPONSE\020"
    "\304\010\022&\n!MSGID_REGAUTH_AUTHACCOUNT_REQUEST\020"
    "\305\010\022\'\n\"MSGID_REGAUTH_AUTHACCOUNT_RESPONSE"
    "\020\360\016\022!\n\034MSGID_REGAUTH_UPDATE_REQUEST\020\361\016\022\""
    "\n\035MSGID_REGAUTH_UPDATE_RESPONSE\020\362\016\022#\n\036MS"
    "GID_WORLD_ZONECHANGED_NOTIFY\020\326\010\022#\n\036MSGID"
    "_WORLD_CREATEROLE_REQUEST\020\327\010\022$\n\037MSGID_WO"
    "RLD_CREATEROLE_RESPONSE\020\330\010\022\"\n\035MSGID_WORL"
    "D_FETCHROLE_REQUEST\020\331\010\022#\n\036MSGID_WORLD_FE"
    "TCHROLE_RESPONSE\020\332\010\022#\n\036MSGID_WORLD_UPDAT"
    "EROLE_REQUEST\020\333\010\022$\n\037MSGID_WORLD_UPDATERO"
    "LE_RESPONSE\020\334\010\022!\n\034MSGID_WORLD_KICKROLE_R"
    "EQUEST\020\335\010\022\"\n\035MSGID_WORLD_KICKROLE_RESPON"
    "SE\020\336\010\022#\n\036MSGID_WORLD_ONLINESTAT_REQUEST\020"
    "\337\010\022$\n\037MSGID_WORLD_ONLINESTAT_RESPONSE\020\340\010"
    "\022\034\n\027MSGID_WORLD_CHAT_NOTIFY\020\341\010\022\035\n\030MSGID_"
    "ZONE_LOGOUT_NOTIFY\020\224\n\022\"\n\035MSGID_ZONE_FRIE"
    "NDINFO_REQUEST\020\225\n\022#\n\036MSGID_ZONE_FRIENDIN"
    "FO_RESPONSE\020\226\n\022#\n\036MSGID_ZONE_LOGINSERVER"
    "_REQUEST\020\227\n\022$\n\037MSGID_ZONE_LOGINSERVER_RE"
    "SPONSE\020\230\n\022%\n MSGID_ZONE_ONLINEROLENUM_RE"
    "QUEST\020\231\n\022\"\n\035MSGID_ZONE_GAMEMASTER_REQUES"
    "T\020\232\n\022#\n\036MSGID_ZONE_GAMEMASTER_RESPONSE\020\233"
    "\n\022\"\n\035MSGID_ZONE_LOGINSERVER_NOTIFY\020\237\n\022 \n"
    "\033MSGID_ZONE_REPOPERA_REQUEST\020\246\n\022!\n\034MSGID"
    "_ZONE_REPOPERA_RESPONSE\020\247\n\022\"\n\035MSGID_ZONE"
    "_GETREPINFO_REQUEST\020\250\n\022#\n\036MSGID_ZONE_GET"
    "REPINFO_RESPONSE\020\251\n\022!\n\034MSGID_ZONE_WEAREQ"
    "UIP_REQUEST\020\252\n\022\"\n\035MSGID_ZONE_WEAREQUIP_R"
    "ESPONSE\020\253\n\022 \n\033MSGID_ZONE_REPCHANGE_NOTIF"
    "Y\020\254\n\022\034\n\027MSGID_ZONE_CHAT_REQUEST\020\262\n\022\035\n\030MS"
    "GID_ZONE_CHAT_RESPONSE\020\263\n\022 \n\033MSGID_ZONE_"
    "SELLITEM_REQUEST\020\264\n\022!\n\034MSGID_ZONE_SELLIT"
    "EM_RESPONSE\020\265\n\022 \n\033MSGID_ZONE_DOCOMBAT_RE"
    "QUEST\020\266\n\022!\n\034MSGID_ZONE_DOCOMBAT_RESPONSE"
    "\020\267\n\022\"\n\035MSGID_ZONE_COMBATMOVE_REUQEST\020\270\n\022"
    "#\n\036MSGID_ZONE_COMBATMOVE_RESPONSE\020\271\n\022$\n\037"
    "MSGID_ZONE_COMBATACTION_REQUEST\020\272\n\022%\n MS"
    "GID_ZONE_COMBATACTION_RESPONSE\020\273\n\022\"\n\035MSG"
    "ID_ZONE_BATTLEFIELD_NOTIFY\020\300\n\022!\n\034MSGID_Z"
    "ONE_COMBATMOVE_NOTIFY\020\301\n\022#\n\036MSGID_ZONE_C"
    "OMBATACTION_NOTIFY\020\302\n\022 \n\033MSGID_ZONE_FINC"
    "OMBAT_NOTIFY\020\303\n\022$\n\037MSGID_ZONE_UNITDIRECT"
    "IVE_NOTIFY\020\317\n\022\'\n\"MSGID_ZONE_UPDATEPARTNE"
    "RAI_REQUEST\020\326\n\022(\n#MSGID_ZONE_UPDATEPARTN"
    "ERAI_RESPONSE\020\327\n\022$\n\037MSGID_ZONE_COMBATADD"
    "BUFF_NOTIFY\020\330\n\022#\n\036MSGID_ZONE_DOBUFFEFFEC"
    "T_NOTIFY\020\331\n\022!\n\034MSGID_ZONE_REMOVEBUFF_NOT"
    "IFY\020\332\n\022$\n\037MSGID_ZONE_ADDCOMBATUNIT_NOTIF"
    "Y\020\373\n\022%\n MSGID_ZONE_KILLCOMBATUNIT_NOTIFY"
    "\020\374\n\022 \n\033MSGID_ZONE_FIGHTATTR_NOTIFY\020\376\n\022$\n"
    "\037MSGID_ZONE_ADDCOMBATTRAP_NOTIFY\020\201\013\022\"\n\035M"
    "SGID_ZONE_TRIGGERTRAP_NOTIFY\020\202\013\022\'\n\"MSGID"
    "_ZONE_DELETECOMBATTRAP_NOTIFY\020\203\013\022%\n MSGI"
    "D_ZONE_UNITATTRCHANGE_NOTIFY\020\204\013\022&\n!MSGID"
    "_ZONE_STARTPVPCOMBAT_REQUEST\020\205\013\022\'\n\"MSGID"
    "_ZONE_STARTPVPCOMBAT_RESPONSE\020\206\013\022&\n!MSGI"
    "D_ZONE_STARTPVPCOMBAT_NBOTIFY\020\207\013\022\'\n\"MSGI"
    "D_ZONE_ACCEPTPVPCOMBAT_REQUEST\020\210\013\022(\n#MSG"
    "ID_ZONE_ACCEPTPVPCOMBAT_RESPONSE\020\211\013\022(\n#M"
    "SGID_ZONE_BEGINCOMBATACTION_NOTIFY\020\212\013\022%\n"
    " MSGID_ZONE_SETCOMBATFORM_REQUEST\020\220\013\022&\n!"
    "MSGID_ZONE_SETCOMBATFORM_RESPONSE\020\221\013\022$\n\037"
    "MSGID_ZONE_SETCOMBATFORM_NOTIFY\020\222\013\022&\n!MS"
    "GID_ZONE_REJECTPVPCOMBAT_NOTIFY\020\227\013\022\'\n\"MS"
    "GID_ZONE_DECREASEUNITBUFF_NOTIFY\020\230\013\022%\n M"
    "SGID_ZONE_ACTIONUNITINFO_NOTIFY\020\231\013\022#\n\036MS"
    "GID_ZONE_SKILLCDROUND_NOTIFY\020\244\013", 3631);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GameProtocol.MsgID.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GameProtocol_2eMsgID_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GameProtocol_2eMsgID_2eproto {
  StaticDescriptorInitializer_GameProtocol_2eMsgID_2eproto() {
    protobuf_AddDesc_GameProtocol_2eMsgID_2eproto();
  }
} static_descriptor_initializer_GameProtocol_2eMsgID_2eproto_;
const ::google::protobuf::EnumDescriptor* ProtocolMsgID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ProtocolMsgID_descriptor_;
}
bool ProtocolMsgID_IsValid(int value) {
  switch(value) {
    case 0:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
    case 1010:
    case 1011:
    case 1012:
    case 1013:
    case 1080:
    case 1081:
    case 1082:
    case 1083:
    case 1084:
    case 1085:
    case 1086:
    case 1087:
    case 1091:
    case 1092:
    case 1093:
    case 1110:
    case 1111:
    case 1112:
    case 1113:
    case 1114:
    case 1115:
    case 1116:
    case 1117:
    case 1118:
    case 1119:
    case 1120:
    case 1121:
    case 1300:
    case 1301:
    case 1302:
    case 1303:
    case 1304:
    case 1305:
    case 1306:
    case 1307:
    case 1311:
    case 1318:
    case 1319:
    case 1320:
    case 1321:
    case 1322:
    case 1323:
    case 1324:
    case 1330:
    case 1331:
    case 1332:
    case 1333:
    case 1334:
    case 1335:
    case 1336:
    case 1337:
    case 1338:
    case 1339:
    case 1344:
    case 1345:
    case 1346:
    case 1347:
    case 1359:
    case 1366:
    case 1367:
    case 1368:
    case 1369:
    case 1370:
    case 1403:
    case 1404:
    case 1406:
    case 1409:
    case 1410:
    case 1411:
    case 1412:
    case 1413:
    case 1414:
    case 1415:
    case 1416:
    case 1417:
    case 1418:
    case 1424:
    case 1425:
    case 1426:
    case 1431:
    case 1432:
    case 1433:
    case 1444:
    case 1904:
    case 1905:
    case 1906:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
